# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  deploy:
    docker:
      - image: circleci/ruby:2.5.3-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: access server
          command: ssh rails@206.189.152.122
      - run:
          name: update
          command: /home/rails/url_shortener/bin/update