# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "77:fe:68:96:9c:cf:4f:80:bc:97:6c:1a:7c:79:6a:7f"
            - "9jkX0XuOT9ASnnPhe98R6PofPE5kioYwTM+d5cd5e38"
      - run:
          name: add host
          command: echo '206.189.152.122 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBOJV2P+Gof/pH6QRl2n18dySJwLU/TMdk0wCFFWTUsfFiAUzTQjNa3I/kA7ebhmcry1Z1hh+Qn42MCF0l9Y8jtU=' >> ~/.ssh/known_hosts
      - run:
          name: access server and update
          command: ssh rails@206.189.152.122 "cd /home/rails/url_shortener && bin/update"