# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "77:fe:68:96:9c:cf:4f:80:bc:97:6c:1a:7c:79:6a:7f"
      - run:
          name: access server
          command: ssh rails@206.189.152.122
      - run:
          name: update
          command: /home/rails/url_shortener/bin/update